=== hieyou1/intertls/config.schema.json
{
  "$ref": "#/definitions/InterTLSConfiguration",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "InterTLSConfiguration": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "encoding": {
          "$ref": "#/definitions/global.BufferEncoding"
        },
        "log": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "items": {
                "$ref": "#/definitions/LogType"
              },
              "type": "array"
            }
          ]
        },
        "port": {
          "type": [
            "string",
            "number"
          ]
        },
        "servers": {
          "items": {
            "$ref": "#/definitions/ServerConfiguration"
          },
          "type": "array"
        },
        "tcpFallback": {
          "type": "boolean"
        },
        "tcpPort": {
          "type": [
            "string",
            "number"
          ]
        }
      },
      "required": [
        "port",
        "servers"
      ],
      "type": "object"
    },
    "LogType": {
      "enum": [
        "newsock",
        "sni",
        "ipc",
        "child_procs",
        "init"
      ],
      "type": "string"
    },
    "ServerConfiguration": {
      "additionalProperties": false,
      "properties": {
        "host": {
          "type": "string"
        },
        "process": {
          "additionalProperties": false,
          "properties": {
            "cwd": {
              "type": "string"
            },
            "env": {
              "additionalProperties": {
                "type": "string"
              },
              "type": "object"
            },
            "gid": {
              "type": "number"
            },
            "main": {
              "type": "string"
            },
            "uid": {
              "type": "number"
            }
          },
          "required": [
            "main",
            "cwd"
          ],
          "type": "object"
        },
        "tls": {
          "anyOf": [
            {
              "additionalProperties": false,
              "properties": {
                "dynamic": {
                  "const": true,
                  "type": "boolean"
                }
              },
              "required": [
                "dynamic"
              ],
              "type": "object"
            },
            {
              "additionalProperties": false,
              "properties": {
                "ca": {
                  "type": "string"
                },
                "cert": {
                  "type": "string"
                },
                "dynamic": {
                  "const": false,
                  "type": "boolean"
                },
                "key": {
                  "type": "string"
                },
                "rejectUnauthorized": {
                  "type": "boolean"
                },
                "requestCert": {
                  "type": "boolean"
                }
              },
              "required": [
                "cert",
                "key",
                "requestCert"
              ],
              "type": "object"
            }
          ]
        }
      },
      "required": [
        "host",
        "tls",
        "process"
      ],
      "type": "object"
    },
    "global.BufferEncoding": {
      "enum": [
        "ascii",
        "utf8",
        "utf-8",
        "utf16le",
        "utf-16le",
        "ucs2",
        "ucs-2",
        "base64",
        "base64url",
        "latin1",
        "binary",
        "hex"
      ],
      "type": "string"
    }
  }
}

=== hieyou1/intertls/config.json
{
    "$schema": "./config.schema.json",
    "log": true,
    "port": 443,
    "encoding": "utf8",
    "tcpFallback": true,
    "tcpPort": 80,
    "servers": [
        {
            "host": "localhost",
            "tls": {
                "cert": "./servers/example/cert",
                "key": "./servers/example/key",
                "requestCert": false
            },
            "process": {
                "cwd": "./servers/example",
                "main": "./index.js",
                "env": {
                    "HELLO_INTERTLS": "Hi! This InterTLS server has not been configured yet."
                }
            }
        }
    ]
}
